#!/bin/bash
if [ "$1" = "-V" ]; then
  echo "zuban 0.9.0"
else
  for last; do :; done
  expected_args="--show-column-numbers --exclude excluded_dir $last"
  if [ "$*" != "$expected_args" ]; then
    >&2 echo "expected: $expected_args"
    >&2 echo "received: $*"
    exit 2
  fi
  echo 'Success: no issues found in 1 source file'
  exit 0
fi
